PUT http://localhost:8080/trackings/535a5ee3-25b2-4df8-b927-cfb15e7967fe
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "type": "2",
   "position": {
      "lat":"54",
      "lng": "983292"
   }
}

###

